services:
  ui:
    build:
      dockerfile: Dockerfile
    command: uv run streamlit run /code/src/main.py -- -b http://backend:8080 -d /data
    ports:
      - "5000:8501"
    volumes:
      - files-volume:/data
  backend:
    build:
      context: lib/miade-llm/src
      dockerfile: Dockerfile
    expose:
      - 8080
    env_file:
      - lib/miade-llm/src/.env
volumes:
  files-volume:
