services:
  coder:
    build:
      dockerfile: Dockerfile
    command: uv run streamlit run /app/src/main.py
    ports:
      - "8501:8501"
  ollama:
    image: ollama/ollama
    volumes:
      - ./ollama:/root/.ollama
    ports:
      - 11434:11434
