services:
  ui:
    build:
      dockerfile: Dockerfile
    command: uv run streamlit run /code/src/main.py --server.address 0.0.0.0 -- -b http://backend:8080 -d /data
    ports:
      - "8501:8501"
    volumes:
      - files-volume:/data
  backend:
    build:
      context: lib/miade-llm/src
      dockerfile: Dockerfile
    expose:
      - 8080
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
    env_file:
      - .env
volumes:
  files-volume:
